function HamilExp = DoublePendulumEnergy(in1,in2)
%DOUBLEPENDULUMENERGY
%    HAMILEXP = DOUBLEPENDULUMENERGY(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    21-Sep-2019 22:29:59

dz1 = in2(:,1);
dz2 = in2(:,2);
z1 = in1(:,1);
z2 = in1(:,2);
HamilExp = cos(z1).*(2.09e2./2.0e2)+cos(z2).*3.268e-1+dz1.^2.*1.376e-2+dz2.^2.*3.272e-3+dz1.*dz2.*cos(z1-z2).*8.885000000000001e-3;
