function out1 = Sindy_ODE_RHS(in1,in2)
%SINDY_ODE_RHS
%    OUT1 = SINDY_ODE_RHS(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    31-Jul-2019 21:06:56

dz1 = in2(:,1);
dz2 = in2(:,2);
dz4 = in2(:,4);
z1 = in1(:,1);
z2 = in1(:,2);
t2 = z2.*-1.0;
t3 = t2+z1;
out1 = dz1.*-3.235001066692433e-2+dz2.*6.00492565527997e-3+sin(z1).*3.796608727034097e1-dz2.^2.*sin(t3).*3.229288227581633e-1-dz4.*cos(t3).*3.229288227581664e-1;
