function Sindy_ODEs = Sindy_ODE_RHS(t,in2,u1)
%SINDY_ODE_RHS
%    SINDY_ODES = SINDY_ODE_RHS(T,IN2,U1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    27-Jul-2019 18:36:20

z1 = in2(:,1);
z3 = in2(:,3);
z4 = in2(:,4);
t2 = cos(z1);
t3 = cos(z3);
t4 = z1.*2.0;
t5 = sin(t4);
t6 = t2.^2;
t7 = z3.^2;
t8 = sin(z1);
Sindy_ODEs = [z3;z4;((t3.*-1.8662e4+u1.*1.5855e4+cos(z1+1.519100000001345).*1.0428e6+cos(t4).*2.3319e4+t5.*t7.*6.0065e3+t5.*z1.^2.*5.7025e3-t5.*z4.^2.*7.7475e3+2.3319e4).*-1.0)./(t2.*1.775e4-t3.*1.0717e4-t6.*6.9604e4+1.0e5);((t5.*-1.8361e5+t8.*1.0425e5+u1.*2.1413e4+t3.*t8.*1.1624e5+t5.*t7.*9.8695e3+t7.*t8.*2.3356e4-t8.*cos(z4).*1.6653e4).*-1.0)./(t6.*4.4259e4-5.0e4)];
