function Eqns = SinglePendulum_ODE(t,in2,F,M,m,L,g)
%SINGLEPENDULUM_ODE
%    EQNS = SINGLEPENDULUM_ODE(T,IN2,F,M,M,L,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    26-Jul-2019 14:09:10

z1 = in2(:,1);
z3 = in2(:,3);
z4 = in2(:,4);
t2 = cos(z1);
t3 = sin(z1);
t4 = t2.^2;
t5 = M+m-m.*t4;
t6 = 1.0./t5;
t7 = z3.^2;
Eqns = [z3;z4;-(t6.*(F.*t2-M.*g.*t3-g.*m.*t3+L.*m.*t2.*t3.*t7))./L;t6.*(F+L.*m.*t3.*t7-g.*m.*t2.*t3)];
