function f_x = ParFor1(in1)
%PARFOR1
%    F_X = PARFOR1(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:34

u = in1(:,1);
ux = in1(:,4);
uxx = in1(:,5);
uxxx = in1(:,6);
f_x = (u.*2.068483425042432e16+ux.*1.324249170136269e16+uxx.*2.430232465385718e17-uxxx.*9.227203045982208e15-u.*ux.*1.026697785691341e16+u.*uxx.*1.006771354523402e17+u.*uxxx.*1.003517386299802e16-5.20598955057152e15)./(u.*6.252226221165773e16+9.513121147676262e16);
