function f_x = ParFor4(in1)
%PARFOR4
%    F_X = PARFOR4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:35

u = in1(:,1);
ux = in1(:,4);
uxx = in1(:,5);
uxxx = in1(:,6);
f_x = ((u.*1.807785219463578e16+ux.*2.87844038948516e19+uxx.*1.111806867891814e17-uxxx.*7.848202243764388e17-u.*ux.*2.277629423136014e19-u.*uxxx.*3.623747593487516e18+4.461317998952448e15).*-1.0)./(u.*6.942494202789888e15-2.602608832707297e17);
