function f_x = ParFor6(in1)
%PARFOR6
%    F_X = PARFOR6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:36

u = in1(:,1);
ux = in1(:,4);
uxx = in1(:,5);
uxxx = in1(:,6);
f_x = ((u.*1.309155212889293e16+ux.*2.877871554164897e19-uxxx.*7.221239403941724e17-u.*ux.*2.27733979415047e19+u.*uxx.*5.233591169266483e16-u.*uxxx.*3.70343657693669e18+4.818811504754688e15).*-1.0)./(u.*1.496263747187507e16-2.174457435992883e17);
