function f_x = ParFor21(in1)
%PARFOR21
%    F_X = PARFOR21(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Jul-2019 11:21:54

u = in1(:,1);
ux = in1(:,4);
uxxx = in1(:,6);
f_x = (u.*4.522798335665357e-1-u.*ux.*4.845857462196363e-1+u.*uxxx.*1.601717324438505e1-3.661177311905703e-1)./u;
