function f_x = ParFor14(in1)
%PARFOR14
%    F_X = PARFOR14(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:38

u = in1(:,1);
ux = in1(:,4);
uxxx = in1(:,6);
f_x = ((ux.*-2.895410174450939e19+uxxx.*2.0816405633874e18+u.*ux.*2.276963278976451e19).*-1.402326054557642e-16)./u;
