function f_x = ParFor3(in1)
%PARFOR3
%    F_X = PARFOR3(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:35

u = in1(:,1);
ux = in1(:,4);
uxx = in1(:,5);
uxxx = in1(:,6);
f_x = (u.*1.034220113405542e16+ux.*6.575036155887616e15+uxx.*1.215253266628608e17-uxxx.*4.601209472843776e15-u.*ux.*5.099459193028608e15+u.*uxx.*5.032641492680704e16+u.*uxxx.*4.967741975658496e15-2.603211137867776e15)./(u.*3.126267420934144e16+4.755897990407782e16);
