function f_x = ParFor16(in1)
%PARFOR16
%    F_X = PARFOR16(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Jul-2019 11:21:52

u = in1(:,1);
ux = in1(:,4);
uxxx = in1(:,6);
f_x = (u.*4.119859153333891e-1+uxxx.*1.312511068413733e1-u.*ux.*9.352580652102915e-1-3.300578856897118e-1)./u;
