function f_x = ParFor9(in1)
%PARFOR9
%    F_X = PARFOR9(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:36

u = in1(:,1);
ux = in1(:,4);
uxxx = in1(:,6);
f_x = ((u.*2.782126712717312e15+ux.*2.304740651558052e20-uxxx.*7.270066527515181e18-u.*ux.*1.822857820176782e20-u.*uxxx.*2.670258726489607e19+4.622981298176e15).*1.878716471683934e-17)./u;
