function f_x = ParFor8(in1)
%PARFOR8
%    F_X = PARFOR8(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:36

u = in1(:,1);
ux = in1(:,4);
uxxx = in1(:,6);
f_x = ((u.*2.695085111689216e15+ux.*2.303219066557725e20-uxxx.*6.644012673329529e18-u.*ux.*1.822348780915927e20-u.*uxxx.*2.846767871024326e19+4.655188118634496e15).*1.893716063443821e-17)./u;
