function f_x = ParFor22(in1)
%PARFOR22
%    F_X = PARFOR22(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Jul-2019 11:21:54

ux = in1(:,4);
uxx = in1(:,5);
f_x = ux.*1.021474096160091-uxx.*1.829051263786823+1.491073398287881e-1;
