function f_x = ParFor12(in1)
%PARFOR12
%    F_X = PARFOR12(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:37

u = in1(:,1);
ux = in1(:,4);
uxxx = in1(:,6);
f_x = ((ux.*-2.895407611355385e19+uxxx.*2.082314376437563e18+u.*ux.*2.27696037536381e19).*-1.347290066700484e-16)./u;
