function f_x = ParFor11(in1)
%PARFOR11
%    F_X = PARFOR11(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:37

u = in1(:,1);
ux = in1(:,4);
uxx = in1(:,5);
uxxx = in1(:,6);
f_x = (u.*4.939829202850415e18+uxx.*4.601879668163871e19+uxxx.*9.043212597120205e16+u.*ux.*6.148352295763968e15+3.747463531950244e17)./(u.*1.925952193953792e18+5.743281611619277e19);
