function f_x = ParFor5(in1)
%PARFOR5
%    F_X = PARFOR5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    20-Sep-2019 09:35:35

u = in1(:,1);
ux = in1(:,4);
uxx = in1(:,5);
uxxx = in1(:,6);
f_x = ((u.*7.604652919865344e15+ux.*1.439296854415953e19+uxx.*4.056295991410688e16-uxxx.*3.942428646215516e17-u.*ux.*1.138844935991067e19-u.*uxxx.*1.804892689519346e18+2.199453572808704e15).*-1.0)./(u.*4.656689920376832e15-1.151078656075366e17);
