function f_x = ParFor10(in1)
%PARFOR10
%    F_X = PARFOR10(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Jul-2019 11:57:29

u = in1(:,1);
uxx = in1(:,5);
f_x = (uxx.*-1.57974309709607)./(u-1.4728218492819);
