function f_x = ParFor8(in1)
%PARFOR8
%    F_X = PARFOR8(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Jul-2019 11:57:28

u = in1(:,1);
uxx = in1(:,5);
f_x = (u.*9.981631376631412e-1+uxx.*9.965561702440027+u.*uxx.*1.006065455272619)./(u+9.978905414318433);
