function Sindy_ODEs = Sindy_ODE_RHS(t,in2,in3)
%SINDY_ODE_RHS
%    SINDY_ODES = SINDY_ODE_RHS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    29-Jul-2019 21:31:37

z1 = in2(1,:);
z2 = in2(2,:);
z3 = in2(3,:);
z4 = in2(4,:);
t4 = z2.*-1.0;
t5 = t4+z1;
t2 = cos(t5);
t3 = z2.*-2.0;
t6 = t2.^2;
t7 = t6.*4.384534e6;
t8 = t7-1.0e7;
t9 = 1.0./t8;
t10 = z1.*2.0;
t11 = z4.^2;
t12 = t3+t10;
t13 = sin(t12);
t14 = z3.^2;
t15 = sin(t5);
Sindy_ODEs = [z3;z4;t9.*(sin(t3+z1).*8.063795e7+sin(z1).*2.990229e8-t11.*t15.*3.229288e6-t13.*t14.*2.192267e6).*-1.0;t9.*(sin(t4+t10).*-2.577404e8+sin(z2).*2.416758e8+t11.*t13.*2.192267e6+t14.*t15.*1.35774e7).*-1.0];
